# Generated by Django 5.2 on 2025-05-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
