# Generated by Django 5.2 on 2025-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_user_wallet_address_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
